- name: modprobe uio
  modprobe: name=uio state=present
  become: yes

- name: rmmod igb_uio
  shell: "rmmod igb_uio"
  become: yes
  changed_when: no
  failed_when: no
  when: lagopus.compile == true

- name: rmmod rte_kni
  shell: "rmmod rte_kni"
  become: yes
  changed_when: no
  failed_when: no
  when: lagopus.compile == true

- name: insmod igb_uio.ko
  shell: "insmod {{ lagopus.src_dir }}/src/dpdk/build/kmod/igb_uio.ko"
  register: res
  changed_when: no
  failed_when: "'No such file or directory' in res.stderr"
  become: yes

- name: insmod rte_kni.ko
  shell: "insmod {{ lagopus.src_dir }}/src/dpdk/build/kmod/rte_kni.ko"
  register: res
  changed_when: no
  failed_when: "'No such file or directory' in res.stderr"
  become: yes

- name: link down intarfaces to bind dpdk
  shell: "ip link set down dev {{ item }}"
  with_items: dpdk_ifaces.physical
  changed_when: no
  failed_when: no
  become: yes

- name: bind dpdk
  shell: "{{ lagopus.src_dir }}/src/dpdk/tools/dpdk_nic_bind.py -b igb_uio {{ item }}"
  with_items: dpdk_ifaces.physical
  changed_when: no
  failed_when: no
  become: yes
