## setup Lagopus

- name: Install packages for Lagopus
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - git
    - build-essential
    - libexpat1-dev
    - libgmp-dev
    - libssl-dev
    - libpcap-dev
    - byacc
    - flex
    - python-dev
    - python-pastedeploy
    - python-paste
    - python-twisted
  environment: "{{ proxy_env }}"
  become: yes

- name: Clone Lagopus from Github
  git:
    repo: "{{ lagopus.repository }}"
    version: "{{ lagopus.version }}"
    dest: "{{ lagopus.src_dir }}"
  environment: "{{ proxy_env }}"
  register: res
  become: yes
  changed_when: res.before != res.after
  when: lagopus.compile == true

- name: configure lagopus
  shell:
    ./configure {{ lagopus.configure_option }}
    chdir={{ lagopus.src_dir }}
  become: yes
  register: configure_lagopus
  changed_when: no
  when: lagopus.compile == true

- name: make lagopus
  shell:
    make {{ lagopus.make_option }}
    chdir={{ lagopus.src_dir }}
  become: yes
  changed_when: no
  when: lagopus.compile == true

- name: make install lagopus
  shell:
    make install
    chdir={{ lagopus.src_dir }}
  become: yes
  changed_when: no
  when: lagopus.compile == true

- name: lagopus config file directory
  file: path=/usr/local/etc/lagopus state=directory owner=root group=root mode=0755
  become: yes


## setup Hugepages

- name: Setup the number of hugepages
  shell: >
    cat /sys/devices/system/node/node{{ item.id }}/hugepages/hugepages-{{ hugepage.size }}/nr_hugepages
    && echo {{ item.number_of_pages }} > /sys/devices/system/node/node{{ item.id }}/hugepages/hugepages-{{ hugepage.size }}/nr_hugepages
  with_items: "{{ hugepage.nodes }}"
  register: result
  become: yes
  when: hugepage.setup == true
  changed_when: result.stdout != "{{ item.number_of_pages }}"

- file: path=/mnt/huge state=directory owner=root group=root mode=0755 recurse=yes
  become: yes
- name: Mount hugepage
  mount: name=/mnt/huge fstype=hugetlbfs src=nodev state=present
  become: yes

## setup DPDK

- include: dpdk.yml


## make lagopus.dsl

- name: make lagopus.dsl
  template:
    src: lagopus.dsl.j2
    dest: /usr/local/etc/lagopus/lagopus.dsl
  become: yes
