- name: Set result of `uname -r`
  shell: uname -r
  register: uname
- name: Install packages for Intel DPDK
  apt: 
    name={{ item }}
    state=present
  with_items:
    - git
    - make
    - coreutils
    - gcc
    - binutils
    - linux-headers-{{ uname.stdout }}
  sudo: yes
- name: Download DPDK
  git:
    repo=http://dpdk.org/git/dpdk
    dest={{ rte_sdk }}
    version={{ dpdk_version }}
  register: download_dpdk
- shell:
    make install T={{ rte_target }}
    chdir={{ rte_sdk }}
  register: install_dpdk
