- name: Install packages for Ryu
  apt:
    name={{ item }}
    state=present
  with_items:
    - python-setuptools
    - python-pip
    - python-dev
    - libxml2-dev
    - libxslt1-dev
  environment: "{{ proxy_env }}"
  become: yes
- name: Install Ryu with pip
  pip:
    name: ryu
    version: "{{ ryu_version }}"
  environment: "{{ proxy_env }}"
  become: yes
- name: Update six to the latest version
  pip:
    name: six
    state: latest
  environment: "{{ proxy_env }}"
  become: yes
