- name: install qemu and libvirt
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - qemu-kvm
    - qemu-system-x86
    - libvirt-bin
    - bridge-utils
    - virtinst
  become: yes

- name: make script to run qemu with vhost-user
  template:
    src: run_qemu.sh.j2
    dest: "{{ run_qemu_script }}"
